//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Гостиница
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public int IDГород { get; set; }
        public decimal Цена { get; set; }
    
        public virtual Город Город { get; set; }
    }
}
