//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class КлиентТур
    {
        public int ID { get; set; }
        public int IDТура { get; set; }
        public int IDГорода { get; set; }
        public int IDКлиента { get; set; }
        public int IDГостиницы { get; set; }
        public decimal Сумма { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Тур Тур { get; set; }
    }
}
