//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int ID_Сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int ID_Роль { get; set; }
        public string Телефон { get; set; }
        public int Зарег_клиентов { get; set; }
        public int Оформ_туров { get; set; }
        public string Логин { get; set; }
        public int Пароль { get; set; }
        public string Аватар { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
